# Netlify configuration file for AI Talent Bridge

[build]
  # Build command (if needed for future enhancements)
  # command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = "."

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for static assets
[[headers]]
  for = "/jobseeker/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/corporate/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/shared/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# CSS and JS caching
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Redirects for clean URLs (optional)
[[redirects]]
  from = "/jobseeker"
  to = "/jobseeker/"
  status = 301

[[redirects]]
  from = "/corporate"
  to = "/corporate/"
  status = 301

# SPA fallback for both apps (if needed in future)
# [[redirects]]
#   from = "/jobseeker/*"
#   to = "/jobseeker/index.html"
#   status = 200

# [[redirects]]
#   from = "/corporate/*"
#   to = "/corporate/index.html"
#   status = 200